-------------------------------------TABLAS

CREATE TABLE USUARIOS(
	USU_ID NUMERIC(5) NOT NULL,
	USU_LOGIN VARCHAR(40) NOT NULL,
	USU_PASS VARCHAR(40) NOT NULL,
	USU_ADMIN VARCHAR(1) NOT NULL DEFAULT 'N',
	USU_HABILITADO VARCHAR(1) NOT NULL DEFAULT 'S'
);

ALTER TABLE USUARIOS ADD CONSTRAINT USU_PK PRIMARY KEY (USU_ID);
ALTER TABLE USUARIOS ADD CONSTRAINT USU_CK1 CHECK (USU_ADMIN IN ('S','N'));
ALTER TABLE USUARIOS ADD CONSTRAINT USU_CK2 CHECK (USU_HABILITADO IN ('S','N'));

CREATE TABLE DUENOS(
	DUE_ID NUMERIC(5) NOT NULL,
	DUE_NOMBRE VARCHAR(40),
	DUE_CEDULA VARCHAR(10),
	DUE_PASAPORTE VARCHAR(10),
	DUE_TELEFONO VARCHAR(20),
	DUE_CELULAR VARCHAR(20),
	DUE_DIRECCION VARCHAR(1000),
	DUE_CREADO_POR NUMERIC(5),
	DUE_FECHA_CREACION DATETIME,
	DUE_MODIF_POR NUMERIC(5),
	DUE_FECHA_MODIF DATETIME
);


ALTER TABLE DUENOS ADD CONSTRAINT DUE_PK PRIMARY KEY (DUE_ID);

CREATE TABLE RAZAS(
	RAZ_ID NUMERIC(5) NOT NULL,
	RAZ_NOMBRE VARCHAR(40)
);

ALTER TABLE RAZAS ADD CONSTRAINT RAZ_PK PRIMARY KEY (RAZ_ID);

CREATE TABLE PERROS(
	PER_ID NUMERIC(5) NOT NULL,
	PER_NOMBRE VARCHAR(40),
	PER_RAZA NUMERIC(5),
	PER_DUENO_ID NUMERIC(5),
	PER_EDAD NUMERIC(2),
	PER_OBSERVACION VARCHAR(1000),
	PER_CREADO_POR NUMERIC(5),
	PER_FECHA_CREACION DATETIME,
	PER_MODIF_POR NUMERIC(5),
	PER_FECHA_MODIF DATETIME
);

ALTER TABLE PERROS ADD CONSTRAINT PER_PK PRIMARY KEY (PER_ID);
ALTER TABLE PERROS ADD CONSTRAINT PER_FK1 FOREIGN KEY (PER_DUENO_ID) REFERENCES DUENOS(DUE_ID);

CREATE TABLE PASADIAS(
	PAS_ID NUMERIC(5) NOT NULL,
	PAS_PERRO_ID NUMERIC(5) NOT NULL,
	PAS_FECHA DATETIME,
	PAS_HORA_LLEGADA DATETIME,
	PAS_HORA_SALIDA DATETIME,
	PAS_COSTO NUMERIC(4,2),
	PAS_RECARGO NUMERIC(4,2),
	PAS_OBSERVACION VARCHAR(1000),
	PAS_CREADO_POR NUMERIC(5),
	PAS_FECHA_CREACION DATETIME,
	PAS_MODIF_POR NUMERIC(5),
	PAS_FECHA_MODIF DATETIME
);

ALTER TABLE PASADIAS ADD CONSTRAINT PAS_PK PRIMARY KEY (PAS_ID);
ALTER TABLE PASADIAS ADD CONSTRAINT PAS_FK1 FOREIGN KEY (PAS_PERRO_ID) REFERENCES PERROS(PER_ID);

CREATE TABLE HOSPEDAJES(
	HOS_ID NUMERIC(5) NOT NULL,
	HOS_PERRO_ID NUMERIC(5) NOT NULL,
	HOS_FECHA_INICIAL DATETIME,
	HOS_FECHA_FINAL DATETIME,
	HOS_FECHA_LLEGADA DATETIME, --FECHA Y HORA
	HOS_FECHA_SALIDA DATETIME, --FECHA Y HORA
	HOS_COSTO_NOCHE NUMERIC(4,2),
	HOS_RECARGO NUMERIC(4,2),
	HOS_OBSERVACION VARCHAR(1000),
	HOS_CREADO_POR NUMERIC(5),
	HOS_FECHA_CREACION DATETIME,
	HOS_MODIF_POR NUMERIC(5),
	HOS_FECHA_MODIF DATETIME
);

ALTER TABLE HOSPEDAJES ADD CONSTRAINT HOS_PK PRIMARY KEY (HOS_ID);
ALTER TABLE HOSPEDAJES ADD CONSTRAINT HOS_FK1 FOREIGN KEY (HOS_PERRO_ID) REFERENCES PERROS(PER_ID);

CREATE TABLE ENTRENAMIENTOS(
	ENT_ID NUMERIC(5) NOT NULL,
	ENT_PERRO_ID NUMERIC(5) NOT NULL,
	ENT_FECHA_INICIAL DATETIME,
	ENT_FECHA_FINAL DATETIME,
	ENT_COSTO NUMERIC(4,2),
	ENT_MODALIDAD VARCHAR(1),
	ENT_HORARIO VARCHAR(1000),
	ENT_OBSERVACION VARCHAR(1000),
	ENT_CREADO_POR NUMERIC(5),
	ENT_FECHA_CREACION DATETIME,
	ENT_MODIF_POR NUMERIC(5),
	ENT_FECHA_MODIF DATETIME
);

ALTER TABLE ENTRENAMIENTOS ADD CONSTRAINT ENT_PK PRIMARY KEY (ENT_ID);
ALTER TABLE ENTRENAMIENTOS ADD CONSTRAINT ENT_FK1 FOREIGN KEY (ENT_PERRO_ID) REFERENCES PERROS(PER_ID);
ALTER TABLE ENTRENAMIENTOS ADD CONSTRAINT ENT_CK1 CHECK (ENT_MODALIDAD IN('C','D')); --EN CASA, DOMICILIO

CREATE TABLE GUARDERIA(
	GUA_ID NUMERIC(5) NOT NULL,
	GUA_FECHA_INICIAL DATETIME,
	GUA_FECHA_FINAL DATETIME,
	GUA_GRUPO NUMERIC(1),
	GUA_COSTO NUMERIC(4,2),
	GUA_OBSERVACION VARCHAR(1000),
	GUA_CREADO_POR NUMERIC(5),
	GUA_FECHA_CREACION DATETIME,
	GUA_MODIF_POR NUMERIC(5),
	GUA_FECHA_MODIF DATETIME
);

ALTER TABLE GUARDERIA ADD CONSTRAINT GUA_PK PRIMARY KEY (GUA_ID);

CREATE TABLE GUARDERIA_PERROS(
	GUA_PER_GUARDERIA_ID NUMERIC(5) NOT NULL,
	GUA_PER_PERRO_ID NUMERIC(5) NOT NULL,
	GUA_PER_GRUPO NUMERIC(1) NOT NULL
);

ALTER TABLE GUARDERIA_PERROS ADD CONSTRAINT GUA_PER_PK PRIMARY KEY (GUA_PER_GUARDERIA_ID, GUA_PER_PERRO_ID);
ALTER TABLE GUARDERIA_PERROS ADD CONSTRAINT GUA_PER_FK1 FOREIGN KEY (GUA_PER_GUARDERIA_ID) REFERENCES GUARDERIA(GUA_ID);
ALTER TABLE GUARDERIA_PERROS ADD CONSTRAINT GUA_PER_FK2 FOREIGN KEY (GUA_PER_PERRO_ID) REFERENCES PERROS(PER_ID);

CREATE TABLE CONTABILIDAD(
	CON_ID NUMERIC(5) NOT NULL,
	CON_SERVICIO_ID NUMERIC(5) NOT NULL,
	CON_TIPO VARCHAR(1) NOT NULL,
	CON_PERRO_ID NUMERIC(5),
	CON_MONTO NUMERIC(4,2),
	CON_METODO VARCHAR(1),
	CON_FECHA DATETIME,
	CON_OBSERVACION VARCHAR(1000),
	CON_CREADO_POR NUMERIC(5),
	CON_FECHA_CREACION DATETIME,
	CON_MODIF_POR NUMERIC(5),
	CON_FECHA_MODIF DATETIME
);

ALTER TABLE CONTABILIDAD ADD CONSTRAINT CON_PK1 PRIMARY KEY (CON_ID);
ALTER TABLE CONTABILIDAD ADD CONSTRAINT CON_CK1 CHECK (CON_TIPO IN('P','H','E','G')); --PASADIAS,HOSPEDAJES,ENTRENAMIENTOS,GUARDERIAS
ALTER TABLE CONTABILIDAD ADD CONSTRAINT CON_CK2 CHECK (CON_METODO IN('E','A','Y','C')); --EFECTIVO,ACH,YAPPY,CHEQUE

-------------------------------------CREATE

CREATE PROCEDURE CREAR_USUARIO(
	@VV_LOGIN VARCHAR(40),
	@VV_PASS VARCHAR(40))
AS
DECLARE
	@LN_ID NUMERIC(5);
BEGIN 
	SET @LN_ID = (SELECT ISNULL(MAX(USU_ID),0)+1 FROM USUARIOS);
	INSERT INTO USUARIOS(USU_ID,USU_LOGIN,USU_PASS)
	VALUES(@LN_ID,@VV_LOGIN,@VV_PASS);
END;


CREATE PROCEDURE CREAR_DUENO(
	@VV_NOMBRE VARCHAR(40),
	@VV_CEDULA VARCHAR(10),
	@VV_PASAPORTE VARCHAR(10),
	@VV_TELEFONO VARCHAR(20),
	@VV_CELULAR VARCHAR(20),
	@VV_DIRECCION VARCHAR(1000),
	@VN_USU_ID NUMERIC(5))
AS
DECLARE
	@LN_ID NUMERIC(5);
BEGIN 
	SET @LN_ID = (SELECT ISNULL(MAX(DUE_ID),0)+1 FROM DUENOS);
	INSERT INTO DUENOS(DUE_ID,DUE_NOMBRE,DUE_CEDULA,DUE_PASAPORTE,DUE_TELEFONO,DUE_CELULAR,DUE_DIRECCION,DUE_CREADO_POR,DUE_FECHA_CREACION,DUE_MODIF_POR,DUE_FECHA_MODIF)
	VALUES(@LN_ID,@VV_NOMBRE,@VV_CEDULA,@VV_PASAPORTE,@VV_TELEFONO,@VV_CELULAR,@VV_DIRECCION,@VN_USU_ID,SYSDATETIME(),@VN_USU_ID,SYSDATETIME());
END;


CREATE PROCEDURE CREAR_PERRO(
	@VV_NOMBRE VARCHAR(40),
	@VN_RAZA NUMERIC(5),
	@VN_DUENO_ID NUMERIC(5),
	@VN_EDAD NUMERIC(2),
	@VV_OBSERVACION VARCHAR(1000),
	@VN_USU_ID NUMERIC(5))
AS
DECLARE
	@LN_ID NUMERIC(5);
BEGIN 
	SET @LN_ID = (SELECT ISNULL(MAX(PER_ID),0)+1 FROM PERROS);
	INSERT INTO PERROS(PER_ID,PER_NOMBRE,PER_RAZA,PER_DUENO_ID,PER_EDAD,PER_OBSERVACION,PER_CREADO_POR,PER_FECHA_CREACION,PER_MODIF_POR,PER_FECHA_MODIF)
	VALUES(@LN_ID,@VV_NOMBRE,@VN_RAZA,@VN_DUENO_ID,@VN_EDAD,@VV_OBSERVACION,@VN_USU_ID,SYSDATETIME(),@VN_USU_ID,SYSDATETIME());
END;


CREATE PROCEDURE CREAR_PASADIA(
	@VN_PERRO_ID NUMERIC(5),
	@VD_FECHA DATETIME,
	@VD_HORA_LLEGADA DATETIME,
	@VD_HORA_SALIDA DATETIME,
	@VN_COSTO NUMERIC(4,2),
	@VN_RECARGO NUMERIC(4,2),
	@VV_OBSERVACION VARCHAR(1000),
	@VN_USU_ID NUMERIC(5))
AS
DECLARE
	@LN_ID NUMERIC(5);
BEGIN 
	SET @LN_ID = (SELECT ISNULL(MAX(PAS_ID),0)+1 FROM PASADIAS);
	INSERT INTO PASADIAS(PAS_ID,PAS_PERRO_ID,PAS_FECHA,PAS_HORA_LLEGADA,PAS_HORA_SALIDA,PAS_COSTO,PAS_RECARGO,PAS_OBSERVACION,PAS_CREADO_POR,PAS_FECHA_CREACION,PAS_MODIF_POR,PAS_FECHA_MODIF)
	VALUES(@LN_ID,@VN_PERRO_ID,@VD_FECHA,@VD_HORA_LLEGADA,@VD_HORA_SALIDA,@VN_COSTO,@VN_RECARGO,@VV_OBSERVACION,@VN_USU_ID,SYSDATETIME(),@VN_USU_ID,SYSDATETIME());
END;


CREATE PROCEDURE CREAR_HOSPEDAJE(
	@VN_PERRO_ID NUMERIC(5),
	@VD_FECHA_INICIAL DATETIME,
	@VD_FECHA_FINAL DATETIME,
	@VD_FECHA_LLEGADA DATETIME,
	@VD_FECHA_SALIDA DATETIME,
	@VN_COSTO_NOCHE NUMERIC(4,2),
	@VN_RECARGO NUMERIC(4,2),
	@VV_OBSERVACION VARCHAR(1000),
	@VN_USU_ID NUMERIC(5))
AS
DECLARE
	@LN_ID NUMERIC(5);
BEGIN 
	SET @LN_ID = (SELECT ISNULL(MAX(HOS_ID),0)+1 FROM HOSPEDAJES);
	INSERT INTO HOSPEDAJES(HOS_ID,HOS_PERRO_ID,HOS_FECHA_INICIAL,HOS_FECHA_FINAL,HOS_FECHA_LLEGADA,HOS_FECHA_SALIDA,HOS_COSTO_NOCHE,HOS_RECARGO,HOS_OBSERVACION,HOS_CREADO_POR,HOS_FECHA_CREACION,HOS_MODIF_POR,HOS_FECHA_MODIF)
	VALUES(@LN_ID,@VN_PERRO_ID,@VD_FECHA_INICIAL,@VD_FECHA_FINAL,@VD_FECHA_LLEGADA,@VD_FECHA_SALIDA,@VN_COSTO_NOCHE,@VN_RECARGO,@VV_OBSERVACION,@VN_USU_ID,SYSDATETIME(),@VN_USU_ID,SYSDATETIME());
END;


CREATE PROCEDURE CREAR_ENTRENAMIENTO(
	@VN_PERRO_ID NUMERIC(5),
	@VD_FECHA_INICIAL DATETIME,
	@VD_FECHA_FINAL DATETIME,
	@VN_COSTO NUMERIC(4,2),
	@VV_MODALIDAD VARCHAR(1),
	@VV_HORARIO VARCHAR(1000),
	@VV_OBSERVACION VARCHAR(1000),
	@VN_USU_ID NUMERIC(5))
AS
DECLARE
	@LN_ID NUMERIC(5);
BEGIN 
	SET @LN_ID = (SELECT ISNULL(MAX(ENT_ID),0)+1 FROM ENTRENAMIENTOS);
	INSERT INTO ENTRENAMIENTOS(ENT_ID,ENT_PERRO_ID,ENT_FECHA_INICIAL,ENT_FECHA_FINAL,ENT_COSTO,ENT_MODALIDAD,ENT_HORARIO,ENT_OBSERVACION,ENT_CREADO_POR,ENT_FECHA_CREACION,ENT_MODIF_POR,ENT_FECHA_MODIF)
	VALUES(@LN_ID,@VN_PERRO_ID,@VD_FECHA_INICIAL,@VD_FECHA_FINAL,@VN_COSTO,@VV_MODALIDAD,@VV_HORARIO,@VV_OBSERVACION,@VN_USU_ID,SYSDATETIME(),@VN_USU_ID,SYSDATETIME());
END;


CREATE PROCEDURE CREAR_GUARDERIA(
	@VD_FECHA_INICIAL DATETIME,
	@VD_FECHA_FINAL DATETIME,
	@VN_GRUPO NUMERIC(1),
	@VN_COSTO NUMERIC(4,2),
	@VV_OBSERVACION VARCHAR(1000),
	@VN_USU_ID NUMERIC(5))
AS
DECLARE
	@LN_ID NUMERIC(5);
BEGIN 
	SET @LN_ID = (SELECT ISNULL(MAX(GUA_ID),0)+1 FROM GUARDERIA);
	INSERT INTO GUARDERIA(GUA_ID,GUA_FECHA_INICIAL,GUA_FECHA_FINAL,GUA_GRUPO,GUA_COSTO,GUA_OBSERVACION,GUA_CREADO_POR,GUA_FECHA_CREACION,GUA_MODIF_POR,GUA_FECHA_MODIF)
	VALUES(@LN_ID,@VD_FECHA_INICIAL,@VD_FECHA_FINAL,@VN_GRUPO,@VN_COSTO,@VV_OBSERVACION,@VN_USU_ID,SYSDATETIME(),@VN_USU_ID,SYSDATETIME());
END;


CREATE PROCEDURE CREAR_PERRO_GUARDERIA(
	@VN_GUARDERIA_ID NUMERIC(5),
	@VN_PERRO_ID NUMERIC(5),
	@VN_GRUPO NUMERIC(1)
)
AS
BEGIN 
	INSERT INTO GUARDERIA_PERROS(GUA_PER_GUARDERIA_ID,GUA_PER_PERRO_ID,GUA_PER_GRUPO)
	VALUES(@VN_GUARDERIA_ID,@VN_PERRO_ID,@VN_GRUPO);
END;


CREATE PROCEDURE CREAR_CONTABILIDAD(
	@VN_SERVICIO_ID NUMERIC(5),
	@VV_TIPO VARCHAR(1),
	@VN_PERRO_ID NUMERIC(5),
	@VN_MONTO NUMERIC(4,2),
	@VV_METODO VARCHAR(1),
	@VD_FECHA DATETIME,
	@VN_OBSERVACION VARCHAR(1000),
	@VN_USU_ID NUMERIC(5))
AS
DECLARE
	@LN_ID NUMERIC(5);
BEGIN 
	SET @LN_ID = (SELECT ISNULL(MAX(CON_ID),0)+1 FROM CONTABILIDAD);
	INSERT INTO CONTABILIDAD(CON_ID,CON_SERVICIO_ID,CON_TIPO,CON_PERRO_ID,CON_MONTO,CON_METODO,CON_FECHA,CON_OBSERVACION,CON_CREADO_POR,CON_FECHA_CREACION,CON_MODIF_POR,CON_FECHA_MODIF)
	VALUES(@LN_ID,@VN_SERVICIO_ID,@VV_TIPO,@VN_PERRO_ID,@VN_MONTO,@VV_METODO,@VD_FECHA,@VN_OBSERVACION,@VN_USU_ID,SYSDATETIME(),@VN_USU_ID,SYSDATETIME());
END;

-------------------------------------UPDATE

CREATE PROCEDURE SP_EDITAR_USUARIO(
	@VN_ID NUMERIC(5),
	@VV_LOGIN VARCHAR(40),
	@VV_PASS VARCHAR(40),
	@VV_ADMIN VARCHAR(1),
	@VV_HABILITADO VARCHAR(1)
)
AS
BEGIN 
	UPDATE USUARIOS SET 
		USU_LOGIN = @VV_LOGIN,
		USU_PASS = @VV_PASS,
		USU_ADMIN = @VV_ADMIN,
		USU_HABILITADO = @VV_HABILITADO
	WHERE USU_ID = @VN_ID;
END;


CREATE PROCEDURE SP_EDITAR_DUENO(
	@VN_ID NUMERIC(5),
	@VV_NOMBRE VARCHAR(40),
	@VV_CEDULA VARCHAR(10),
	@VV_PASAPORTE VARCHAR(10),
	@VV_TELEFONO VARCHAR(20),
	@VV_CELULAR VARCHAR(20),
	@VV_DIRECCION VARCHAR(1000),
	@VN_USU_ID NUMERIC(5)
)
AS
BEGIN 
	UPDATE DUENOS SET 
		DUE_NOMBRE = @VV_NOMBRE,
		DUE_CEDULA = @VV_CEDULA,
		DUE_PASAPORTE = @VV_PASAPORTE,
		DUE_TELEFONO = @VV_TELEFONO,
		DUE_CELULAR = @VV_CELULAR,
		DUE_DIRECCION = @VV_DIRECCION,
		DUE_MODIF_POR = @VN_USU_ID,
		DUE_FECHA_MODIF = SYSDATETIME()
	WHERE DUE_ID = @VN_ID;
END;


CREATE PROCEDURE SP_EDITAR_PERRO(
	@VN_ID NUMERIC(5),
	@VV_NOMBRE VARCHAR(40),
	@VN_RAZA NUMERIC(5),
	@VN_DUENO_ID NUMERIC(5),
	@VN_EDAD NUMERIC(2),
	@VV_OBSERVACION VARCHAR(1000),
	@VN_USU_ID NUMERIC(5)
)
AS
BEGIN 
	UPDATE PERROS SET 
		PER_NOMBRE = @VV_NOMBRE,
		PER_RAZA = @VN_RAZA,
		PER_DUENO_ID = @VN_DUENO_ID,
		PER_EDAD = @VN_EDAD,
		PER_OBSERVACION = @VV_OBSERVACION,
		PER_MODIF_POR = @VN_USU_ID,
		PER_FECHA_MODIF = SYSDATETIME()
	WHERE PER_ID = @VN_ID;
END;


CREATE PROCEDURE SP_EDITAR_PASADIA(
	@VN_ID NUMERIC(5),
	@VN_PERRO_ID NUMERIC(5),
	@VD_FECHA DATETIME,
	@VD_HORA_LLEGADA DATETIME,
	@VD_HORA_SALIDA DATETIME,
	@VN_COSTO NUMERIC(4,2),
	@VN_RECARGO NUMERIC(4,2),
	@VV_OBSERVACION VARCHAR(1000),
	@VN_USU_ID NUMERIC(5)
)
AS
BEGIN 
	UPDATE PASADIAS SET 
		PAS_PERRO_ID = @VN_PERRO_ID,
		PAS_FECHA = @VD_FECHA,
		PAS_HORA_LLEGADA = @VD_HORA_LLEGADA,
		PAS_HORA_SALIDA = @VD_HORA_SALIDA,
		PAS_COSTO = @VN_COSTO,
		PAS_RECARGO = @VN_RECARGO,
		PAS_OBSERVACION = @VV_OBSERVACION,
		PAS_MODIF_POR = @VN_USU_ID,
		PAS_FECHA_MODIF = SYSDATETIME()
	WHERE PAS_ID = @VN_ID;
END;


CREATE PROCEDURE SP_EDITAR_HOSPEDAJE(
	@VN_ID NUMERIC(5),
	@VN_PERRO_ID NUMERIC(5),
	@VD_FECHA_INICIAL DATETIME,
	@VD_FECHA_FINAL DATETIME,
	@VD_FECHA_LLEGADA DATETIME,
	@VD_FECHA_SALIDA DATETIME,
	@VN_COSTO_NOCHE NUMERIC(4,2),
	@VN_RECARGO NUMERIC(4,2),
	@VV_OBSERVACION VARCHAR(1000),
	@VN_USU_ID NUMERIC(5)
)
AS
BEGIN 
	UPDATE HOSPEDAJES SET 
		HOS_PERRO_ID = @VN_PERRO_ID,
		HOS_FECHA_INICIAL = @VD_FECHA_INICIAL,
		HOS_FECHA_FINAL = @VD_FECHA_FINAL,
		HOS_FECHA_LLEGADA = @VD_FECHA_LLEGADA,
		HOS_FECHA_SALIDA = @VD_FECHA_SALIDA,
		HOS_COSTO_NOCHE = @VN_COSTO_NOCHE,
		HOS_RECARGO = @VN_RECARGO,
		HOS_OBSERVACION = @VV_OBSERVACION,
		HOS_MODIF_POR = @VN_USU_ID,
		HOS_FECHA_MODIF = SYSDATETIME()
	WHERE HOS_ID = @VN_ID;
END;


CREATE PROCEDURE SP_EDITAR_ENTRENAMIENTO(
	@VN_ID NUMERIC(5),
	@VN_PERRO_ID NUMERIC(5),
	@VD_FECHA_INICIAL DATETIME,
	@VD_FECHA_FINAL DATETIME,
	@VN_COSTO NUMERIC(4,2),
	@VV_MODALIDAD VARCHAR(1),
	@VV_HORARIO VARCHAR(1000),
	@VV_OBSERVACION VARCHAR(1000),
	@VN_USU_ID NUMERIC(5)
)
AS
BEGIN 
	UPDATE ENTRENAMIENTOS SET 
		ENT_PERRO_ID = @VN_PERRO_ID,
		ENT_FECHA_INICIAL = @VD_FECHA_INICIAL,
		ENT_FECHA_FINAL = @VD_FECHA_FINAL,
		ENT_COSTO = @VN_COSTO,
		ENT_MODALIDAD = @VV_MODALIDAD,
		ENT_HORARIO = @VV_HORARIO,
		ENT_OBSERVACION = @VV_OBSERVACION,
		ENT_MODIF_POR = @VN_USU_ID,
		ENT_FECHA_MODIF = SYSDATETIME()
	WHERE ENT_ID = @VN_ID;
END;


CREATE PROCEDURE SP_EDITAR_GUARDERIA(
	@VN_ID NUMERIC(5),
	@VD_FECHA_INICIAL DATETIME,
	@VD_FECHA_FINAL DATETIME,
	@VN_GRUPO NUMERIC(1),
	@VN_COSTO NUMERIC(4,2),
	@VV_OBSERVACION VARCHAR(1000),
	@VN_USU_ID NUMERIC(5)
)
AS
BEGIN 
	UPDATE GUARDERIA SET 
		GUA_FECHA_INICIAL = @VD_FECHA_INICIAL,
		GUA_FECHA_FINAL = @VD_FECHA_FINAL,
		GUA_GRUPO = @VN_GRUPO,
		GUA_COSTO = @VN_COSTO,
		GUA_OBSERVACION = @VV_OBSERVACION,
		GUA_MODIF_POR = @VN_USU_ID,
		GUA_FECHA_MODIF = SYSDATETIME()
	WHERE GUA_ID = @VN_ID;
END;


CREATE PROCEDURE SP_EDITAR_CONTABILIDAD(
	@VN_ID NUMERIC(5),
	@VN_SERVICIO_ID NUMERIC(5),
	@VV_TIPO VARCHAR(1),
	@VN_PERRO_ID NUMERIC(5),
	@VN_MONTO NUMERIC(4,2),
	@VV_METODO VARCHAR(1),
	@VD_FECHA DATETIME,
	@VN_OBSERVACION VARCHAR(1000),
	@VN_USU_ID NUMERIC(5)
)
AS
BEGIN 
	UPDATE CONTABILIDAD SET 
		CON_SERVICIO_ID = @VN_SERVICIO_ID,
		CON_TIPO = @VV_TIPO,
		CON_PERRO_ID = @VN_PERRO_ID,
		CON_MONTO = @VN_MONTO,
		CON_METODO = @VV_METODO,
		CON_FECHA = @VD_FECHA,
		CON_OBSERVACION = @VN_OBSERVACION,
		CON_MODIF_POR = @VN_USU_ID,
		CON_FECHA_MODIF = SYSDATETIME()
	WHERE CON_ID = @VN_ID;
END;

-------------------------------------DELETE 

CREATE PROCEDURE SP_BORRAR_USUARIO(
    @VN_ID NUMERIC(5)
)
AS
BEGIN
    DELETE FROM USUARIOS WHERE USU_ID = @VN_ID;
END;


CREATE PROCEDURE SP_BORRAR_DUENO(
    @VN_ID NUMERIC(5)
)
AS
BEGIN
    DELETE FROM DUENOS WHERE DUE_ID = @VN_ID;
END;


CREATE PROCEDURE SP_BORRAR_PERRO(
    @VN_ID NUMERIC(5)
)
AS
BEGIN
    DELETE FROM PERROS WHERE PER_ID = @VN_ID;
END;


CREATE PROCEDURE SP_BORRAR_PASADIA(
    @VN_ID NUMERIC(5)
)
AS
BEGIN
    DELETE FROM PASADIAS WHERE PAS_ID = @VN_ID;
END;


CREATE PROCEDURE SP_BORRAR_HOSPEDAJE(
    @VN_ID NUMERIC(5)
)
AS
BEGIN
    DELETE FROM HOSPEDAJES WHERE HOS_ID = @VN_ID;
END;


CREATE PROCEDURE SP_BORRAR_ENTRENAMIENTO(
    @VN_ID NUMERIC(5)
)
AS
BEGIN
    DELETE FROM ENTRENAMIENTOS WHERE ENT_ID = @VN_ID;
END;


CREATE PROCEDURE SP_BORRAR_GUARDERIA_PERRO(
    @VN_GUARDERIA_ID NUMERIC(5),
    @VN_PERRO_ID NUMERIC(5),
    @VN_GRUPO NUMERIC(1),
)
AS
BEGIN
    DELETE FROM GUARDERIA_PERROS 
    WHERE 
    	GUA_PER_GUARDERIA_ID = @VN_GUARDERIA_ID AND
    	GUA_PER_PERRO_ID = @VN_PERRO_ID AND
    	GUA_PER_GRUPO = @VN_GRUPO;
END;


CREATE PROCEDURE SP_BORRAR_GUARDERIA(
    @VN_ID NUMERIC(5)
)
AS
BEGIN
    DELETE FROM GUARDERIA WHERE GUA_ID = @VN_ID;
END;

-------------------------------------GET

CREATE PROCEDURE SP_OBTENER_USUARIOS
AS
BEGIN
    SELECT 
	    USU_ID AS ID,
	    USU_LOGIN AS USERNAME,
	    USU_PASS AS PASSWORD,
	    USU_ADMIN AS ADMIN,
	    USU_HABILITADO AS HABILITADO
    FROM USUARIOS;
END;


CREATE PROCEDURE SP_OBTENER_DUENOS
AS
BEGIN
    SELECT 
	    DUE_ID AS ID,
	    DUE_NOMBRE AS NOMBRE,
	    DUE_CEDULA AS CEDULA,
	    DUE_PASAPORTE AS PASAPORTE,
	    DUE_CELULAR AS CELULAR,
	    DUE_TELEFONO AS TELEFONO,
	    DUE_DIRECCION AS DIRECCION,
	    DUE_CREADO_POR AS CREADOPOR,
	    DUE_FECHA_CREACION AS FECHACREA,
	    DUE_MODIF_POR AS MODIFPOR,
	    DUE_FECHA_MODIF AS FECHAMODIF
    FROM DUENOS;
END;


CREATE PROCEDURE SP_OBTENER_RAZAS
AS
BEGIN
    SELECT 
	    RAZ_ID AS ID,
	    RAZ_NOMBRE AS NOMBRE
    FROM RAZAS;
END;


CREATE PROCEDURE SP_OBTENER_PERROS
AS
BEGIN
    SELECT 
	    PER_ID AS ID,
	    PER_NOMBRE AS NOMBRE,
	    PER_RAZA AS RAZA,
	    PER_EDAD AS EDAD,
	    PER_DUENO_ID AS DUENO,
	    PER_OBSERVACION AS OBSERVACION
    FROM PERROS;
END;


CREATE PROCEDURE SP_OBTENER_PASADIAS
AS
BEGIN
    SELECT 
	    PAS_ID AS ID,
	    PAS_PERRO_ID AS PERRO_ID,
	    PAS_FECHA AS FECHA,
	    PAS_HORA_LLEGADA AS HORA_LLEGADA,
	    PAS_HORA_SALIDA AS HORA_SALIDA,
	    PAS_COSTO AS COSTO,
	    PAS_RECARGO AS RECARGO,
	    PAS_OBSERVACION AS OBSERVACION
    FROM PASADIAS;
END;


CREATE PROCEDURE SP_OBTENER_HOSPEDAJES
AS
BEGIN
    SELECT 
	    HOS_ID AS ID,
	    HOS_PERRO_ID AS PERRO_ID,
	    HOS_FECHA_INICIAL AS FECHA_INICAL,
	    HOS_FECHA_FINAL AS FECHA_FINAL,
	    HOS_FECHA_LLEGADA AS FECHA_LLEGADA,
	    HOS_FECHA_SALIDA AS FECHA_SALIDA,
	    HOS_COSTO_NOCHE AS COSTO_NOCHE,
	    HOS_RECARGO AS RECARGO,
	    HOS_OBSERVACION AS OBSERVACION
    FROM HOSPEDAJES;
END;

CREATE PROCEDURE SP_OBTENER_ENTRENAMIENTOS
AS
BEGIN
    SELECT 
	    ENT_ID AS ID,
	    ENT_PERRO_ID AS PERRO_ID,
	    ENT_FECHA_INICIAL AS FECHA_INICAL,
	    ENT_FECHA_FINAL AS FECHA_FINAL,
	    ENT_COSTO AS COSTO,
	    ENT_MODALIDAD AS MODALIDAD,
	    ENT_HORARIO AS HORARIO,
	    ENT_OBSERVACION AS OBSERVACION
    FROM ENTRENAMIENTOS;
END;


CREATE PROCEDURE SP_OBTENER_GUARDERIAS
AS
BEGIN
    SELECT 
	    GUA_ID AS ID,
	    GUA_FECHA_INICIAL AS FECHA_INICAL,
	    GUA_FECHA_FINAL AS FECHA_FINAL,
	    GUA_GRUPO AS GRUPO,
	    GUA_COSTO AS COSTO,
	    GUA_OBSERVACION AS OBSERVACION
    FROM GUARDERIA;
END;


CREATE PROCEDURE SP_OBTENER_PERROS_GUARDERIAS
AS
BEGIN
    SELECT 
	    GUA_PER_GUARDERIA_ID AS GUARDERIA_ID,
	    GUA_PER_PERRO_ID AS PERRO_ID,
	    GUA_PER_GRUPO AS GRUPO
    FROM GUARDERIA_PERROS;
END;


CREATE PROCEDURE SP_OBTENER_CONTABILIDADES
AS
BEGIN
    SELECT 
	    CON_ID AS ID,
	    CON_SERVICIO_ID AS SERVICIO_ID,
	    CON_TIPO AS TIPO,
	    CON_PERRO_ID AS PERRO_ID,
	    CON_MONTO AS MONTO,
	    CON_METODO AS METODO,
	    CON_FECHA AS FECHA,
	    CON_OBSERVACION AS OBSERVACION
    FROM CONTABILIDAD;
END;

-------------------------------------EXEC

EXEC CREAR_USUARIO 
	@VV_LOGIN = "prueba",
	@VV_PASS = "1234";

EXEC CREAR_DUENO
	@VV_NOMBRE = "prueba 2",
	@VV_CEDULA = "123456789",
	@VV_PASAPORTE = "123456789",
	@VV_TELEFONO = "5555555",
	@VV_CELULAR = "ok",
	@VV_DIRECCION = "1",
	@VN_USU_ID = 1;

EXEC CREAR_PERRO(
	@VV_NOMBRE = "PERRO1",
	@VN_RAZA = 1,
	@VN_DUENO_ID = 1,
	@VN_EDAD = 5,
	@VV_OBSERVACION = "",
	@VN_USU_ID = 1;

EXEC CREAR_PASADIA(
	@VN_PERRO_ID = 1,
	@VD_FECHA = SYSDATETIME(),
	@VD_HORA_LLEGADA = SYSDATETIME(),
	@VD_HORA_SALIDA = SYSDATETIME(),
	@VN_COSTO = 20,
	@VN_RECARGO = 5,
	@VV_OBSERVACION = "",
	@VN_USU_ID = 1;

EXEC CREAR_CONTABILIDAD(
	@VN_SERVICIO_ID = 1,
	@VV_TIPO = "P",
	@VN_PERRO_ID = 1,
	@VN_MONTO = 20,
	@VV_METODO = "E",
	@VD_FECHA = SYSDATETIME(),
	@VN_OBSERVACION = "",
	@VN_USU_ID = 1;